### ISSUE TITLE
Doesn't work with multimodule project

### ISSUE THREAD

**Issue by CG-Charlotte** [CodinGame/junit-runner#12]
Hello,

In case of multimodule project, we need to pass the parameter  "-pl" in order to specify the right module. 
http://stackoverflow.com/questions/11869762/maven-run-only-single-test-in-multi-module-project

Can we change the regex pattern to manage this?

**Comment by Sy1v4in** [comment]
I'm not sure to understand. `pl` arg is a comma-delimited list of specified reactor projects to build instead of all projects. Why don't you want to build all your modules?
